---
title: "Data Quality Monitoring Report"
author: "Prepared by TAN Thiam Huat"
date: 'Updated on `r format(Sys.time(), "%a %b %d %X %Y")`'
output:
  html_document: default
  fig_height: 6
  fig_width: 5
  fig_caption: yes
  number_sections: yes
  pdf_document: yes
  toc: yes
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=6, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

## Table of contents
***
This document is updated automatically on a daily basis for the purpose of Data Quality Monitoring of the Water Meters installed in Singapore.

* Data Quality Monitoring Report

    - [Overall Performance]
    - [Tabular Data]
    - [Customers with No Index]

    ## Overall Performance
```{r, echo=FALSE}
dygraph(Index_CCFilesCount_xts, main = "Index & CC Files Availability") %>%
  dyRangeSelector() %>%
  dyAxis("y",label="Index & CC Files Availability (%)",valueRange = c(0, 110)) 
```

    ## Tabular Data
```{r, echo=FALSE}
DT::datatable(Index_CCFilesCount)
```

    ## Customers with No Index
```{r, echo=FALSE}
DT::datatable(missing_service_point_sn)
```